import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  String _currentLanguage = 'English';
  static const String _storageKey = 'language';

  String get currentLanguage => _currentLanguage;

  final Map<String, Map<String, String>> _translations = {
    'English': {
      'appTitle': 'Paws New Home',
      'appSubtitle': 'Find your forever friend',
      'shelters': 'Shelters',
      'animals': 'Animals',
      'adopted': 'Adopted',
      'nearbyShelters': 'Nearby Shelters',
      'seeAll': 'See All',
      'registerShelter': 'Register Shelter',
      'available': 'AVAILABLE',
      'pending': 'PENDING',
      'adopted_status': 'ADOPTED',
      'age': 'Age',
      'gender': 'Gender',
      'weight': 'Weight',
      'about': 'About',
      'gallery': 'Gallery',
      'aboutShelter': 'About the Shelter',
      'donate': 'Donate via PayPal',
      'connectWith': 'Connect with us',
      'meetResidents': 'Meet our Residents',
      'viewAll': 'View All',
      'reviews': 'Reviews',
      'writeReview': 'Write a Review',
      'basicInfo': 'Basic Information',
      'contactSocial': 'Contact & Social',
      'support': 'Support',
      'shelterName': 'Shelter Name',
      'country': 'Country / City',
      'description': 'Description',
      'email': 'Email Address',
      'whatsapp': 'WhatsApp Number',
      'telegram': 'Telegram Username',
      'instagram': 'Instagram Link',
      'paypal': 'PayPal Donation Link',
      'submitRegistration': 'Submit Registration',
      'ourResidents': 'Our Residents',
      'interestedIn': 'Interested in',
      'inquireEmail': 'Inquire via Email',
      'shareExperience': 'Share your experience with this shelter',
      'submitReview': 'Submit Review',
      'recentReviews': 'Recent Reviews',
      'basedOnReviews': 'Based on',
      'sortBy': 'Sort by',
      'male': 'Male',
      'female': 'Female',
      'all': 'All',
      'dogs': 'Dogs',
      'cats': 'Cats',
      'birds': 'Birds',
      'others': 'Others',
      'cantAdopt': "Can't adopt?",
      'supportShelter': 'Support the shelter',
      'donateNow': 'Donate Now',
    },
    'German': {
      'appTitle': 'Paws New Home',
      'appSubtitle': 'Finde deinen Freund fürs Leben',
      'shelters': 'Tierheime',
      'animals': 'Tiere',
      'adopted': 'Adoptiert',
      'nearbyShelters': 'Tierheime in der Nähe',
      'seeAll': 'Alle anzeigen',
      'registerShelter': 'Tierheim registrieren',
      'available': 'VERFÜGBAR',
      'pending': 'AUSSTEHEND',
      'adopted_status': 'ADOPTIERT',
      'age': 'Alter',
      'gender': 'Geschlecht',
      'weight': 'Gewicht',
      'about': 'Über',
      'gallery': 'Galerie',
      'aboutShelter': 'Über das Tierheim',
      'donate': 'Spenden via PayPal',
      'connectWith': 'Kontaktieren Sie uns',
      'meetResidents': 'Unsere Bewohner',
      'viewAll': 'Alle anzeigen',
      'reviews': 'Bewertungen',
      'writeReview': 'Bewertung schreiben',
      'basicInfo': 'Grundinformationen',
      'contactSocial': 'Kontakt & Social Media',
      'support': 'Unterstützung',
      'shelterName': 'Name des Tierheims',
      'country': 'Land / Stadt',
      'description': 'Beschreibung',
      'email': 'E-Mail-Adresse',
      'whatsapp': 'WhatsApp-Nummer',
      'telegram': 'Telegram-Benutzername',
      'instagram': 'Instagram-Link',
      'paypal': 'PayPal-Spendenlink',
      'submitRegistration': 'Registrierung abschicken',
      'ourResidents': 'Unsere Bewohner',
      'interestedIn': 'Interessiert an',
      'inquireEmail': 'Anfrage per E-Mail',
      'shareExperience': 'Teilen Sie Ihre Erfahrung mit diesem Tierheim',
      'submitReview': 'Bewertung abschicken',
      'recentReviews': 'Neueste Bewertungen',
      'basedOnReviews': 'Basierend auf',
      'sortBy': 'Sortieren nach',
      'male': 'Männlich',
      'female': 'Weiblich',
      'all': 'Alle',
      'dogs': 'Hunde',
      'cats': 'Katzen',
      'birds': 'Vögel',
      'others': 'Andere',
      'cantAdopt': 'Nicht adoptieren?',
      'supportShelter': 'Tierheim unterstützen',
      'donateNow': 'Jetzt spenden',
    },
    'Ukrainian': {
      'appTitle': 'Paws New Home',
      'appSubtitle': 'Знайди свого друга назавжди',
      'shelters': 'Притулки',
      'animals': 'Тварини',
      'adopted': 'Усиновлено',
      'nearbyShelters': 'Притулки поблизу',
      'seeAll': 'Показати всі',
      'registerShelter': 'Зареєструвати притулок',
      'available': 'ДОСТУПНИЙ',
      'pending': 'В ОЧІКУВАННІ',
      'adopted_status': 'УСИНОВЛЕНИЙ',
      'age': 'Вік',
      'gender': 'Стать',
      'weight': 'Вага',
      'about': 'Про',
      'gallery': 'Галерея',
      'aboutShelter': 'Про притулок',
      'donate': 'Пожертвувати через PayPal',
      'connectWith': "Зв'яжіться з нами",
      'meetResidents': 'Наші мешканці',
      'viewAll': 'Переглянути все',
      'reviews': 'Відгуки',
      'writeReview': 'Написати відгук',
      'basicInfo': 'Основна інформація',
      'contactSocial': 'Контакти та соцмережі',
      'support': 'Підтримка',
      'shelterName': 'Назва притулку',
      'country': 'Країна / Місто',
      'description': 'Опис',
      'email': 'Електронна пошта',
      'whatsapp': 'Номер WhatsApp',
      'telegram': "Ім'я користувача Telegram",
      'instagram': 'Посилання Instagram',
      'paypal': 'Посилання для пожертв PayPal',
      'submitRegistration': 'Подати реєстрацію',
      'ourResidents': 'Наші мешканці',
      'interestedIn': 'Цікавить',
      'inquireEmail': 'Запит електронною поштою',
      'shareExperience': 'Поділіться своїм досвідом із цим притулком',
      'submitReview': 'Надіслати відгук',
      'recentReviews': 'Останні відгуки',
      'basedOnReviews': 'На основі',
      'sortBy': 'Сортувати за',
      'male': 'Чоловіча',
      'female': 'Жіноча',
      'all': 'Всі',
      'dogs': 'Собаки',
      'cats': 'Коти',
      'birds': 'Птахи',
      'others': 'Інші',
      'cantAdopt': 'Не можете усиновити?',
      'supportShelter': 'Підтримати притулок',
      'donateNow': 'Пожертвувати зараз',
    },
    'Russian': {
      'appTitle': 'Paws New Home',
      'appSubtitle': 'Найди своего друга навсегда',
      'shelters': 'Приюты',
      'animals': 'Животные',
      'adopted': 'Усыновлено',
      'nearbyShelters': 'Ближайшие приюты',
      'seeAll': 'Показать все',
      'registerShelter': 'Зарегистрировать приют',
      'available': 'ДОСТУПЕН',
      'pending': 'В ОЖИДАНИИ',
      'adopted_status': 'УСЫНОВЛЕН',
      'age': 'Возраст',
      'gender': 'Пол',
      'weight': 'Вес',
      'about': 'О',
      'gallery': 'Галерея',
      'aboutShelter': 'О приюте',
      'donate': 'Пожертвовать через PayPal',
      'connectWith': 'Свяжитесь с нами',
      'meetResidents': 'Наши жители',
      'viewAll': 'Посмотреть все',
      'reviews': 'Отзывы',
      'writeReview': 'Написать отзыв',
      'basicInfo': 'Основная информация',
      'contactSocial': 'Контакты и соцсети',
      'support': 'Поддержка',
      'shelterName': 'Название приюта',
      'country': 'Страна / Город',
      'description': 'Описание',
      'email': 'Электронная почта',
      'whatsapp': 'Номер WhatsApp',
      'telegram': 'Имя пользователя Telegram',
      'instagram': 'Ссылка Instagram',
      'paypal': 'Ссылка для пожертвований PayPal',
      'submitRegistration': 'Отправить регистрацию',
      'ourResidents': 'Наши жители',
      'interestedIn': 'Интересует',
      'inquireEmail': 'Запрос по электронной почте',
      'shareExperience': 'Поделитесь своим опытом с этим приютом',
      'submitReview': 'Отправить отзыв',
      'recentReviews': 'Последние отзывы',
      'basedOnReviews': 'На основе',
      'sortBy': 'Сортировать по',
      'male': 'Мужской',
      'female': 'Женский',
      'all': 'Все',
      'dogs': 'Собаки',
      'cats': 'Кошки',
      'birds': 'Птицы',
      'others': 'Другие',
      'cantAdopt': 'Не можете усыновить?',
      'supportShelter': 'Поддержать приют',
      'donateNow': 'Пожертвовать сейчас',
    },
  };

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      _currentLanguage = prefs.getString(_storageKey) ?? 'English';
      notifyListeners();
    } catch (e) {
      // Ignore errors, use default language
    }
  }

  Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    notifyListeners();
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_storageKey, language);
    } catch (e) {
      // Ignore storage errors
    }
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }
}
