// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOei-QNbCNKe71E0zkUkwnCT57aq0uj94',
    appId: '1:267415198748:web:28dc43aff95dc34c1c93d9',
    messagingSenderId: '267415198748',
    projectId: 'paws-without-borders',
    authDomain: 'paws-without-borders.firebaseapp.com',
    storageBucket: 'paws-without-borders.firebasestorage.app',
    measurementId: 'G-R0MQZ61N32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ACluqH7KGCmKMtCIrX_qvgp5ewMay-A',
    appId: '1:267415198748:android:859160db5d67f6fd1c93d9',
    messagingSenderId: '267415198748',
    projectId: 'paws-without-borders',
    storageBucket: 'paws-without-borders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbIPV8Aru3jOy4WXNw7vKHsycCa2gSGM',
    appId: '1:267415198748:ios:485b37f6140cc0e51c93d9',
    messagingSenderId: '267415198748',
    projectId: 'paws-without-borders',
    storageBucket: 'paws-without-borders.firebasestorage.app',
    iosClientId: '267415198748-0embd266psgsbc8liegq7knk9m886rct.apps.googleusercontent.com',
    iosBundleId: 'com.anna.pawswithoutborders',
  );

}