- name: Restore keystore
  run: |
    echo "${{ secrets.UPLOAD_KEYSTORE_B64 }}" | base64 -d > android/upload-keystore.jks

    cat > android/key.properties << EOF
    storeFile=upload-keystore.jks
    storePassword=${{ secrets.UPLOAD_STORE_PASSWORD }}
    keyPassword=${{ secrets.UPLOAD_KEY_PASSWORD }}
    keyAlias=${{ secrets.UPLOAD_KEY_ALIAS }}
    EOF

- name: Build AppBundle (release)
  run: flutter build appbundle --release
